<fieldset>
<legend>NOTICE OF CANCELLATION</legend>						
YOU MAY CANCEL THIS TRANSACTION, WITHOUT PENALTY OR OBLIGATION, WITHIN THREE (3) BUSINESS DAYS OF THE CONTRACT DATE. <br>
TO CANCEL THIS TRANSACTION, MAIL OR DELIVER A SIGNED DATED COPY OF THIS CANCELLATION NOTICE TO AQUA ESSENCE POOLS, L.L.C.<br>
NOTE: PHONE CALLS OR FACSIMILIE COPIES CANNOT BE ACCEPTED IN LEIU OF SIGNED AND DATED NOTICE OF CANCELLATION.	<br>	
I HEREBY CANCEL THIS TRANSACTION:	I HEREBY CANCEL THIS TRANSACTION.                                                              Buyer:________________date:__/__/____									
		
</fieldset>